In [9]:
!pip install numpy

In [10]:
import numpy as np

In [12]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.shape

(5,)

In [8]:
arr.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [ ]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[7,5,9,8,6]

arr=np.array([my_lst1, my_lst2, my_lst3])

In [ ]:
# arr

In [ ]:
# arr.shape
arr.reshape(15,1)

In [ ]:
# arr.reshape(5,3)

In [ ]:
# arr.reshape(1,15)

## indexing

In [122]:
 arr=np.array([1,2,3,4,5,6,7,8,9])

In [113]:
# arr[3]

In [114]:
# arr

In [115]:
# arr.reshape(5,3)

In [124]:
# arr[1:2,1:4]

In [125]:
# arr=np.arange(0,10,step=2)

In [126]:
# arr

In [127]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [128]:
arr[3:]=100

In [132]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [133]:
arr1=arr

In [134]:
arr1[3:]=500
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [135]:
arr1=arr.copy()

In [136]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [142]:
var=2

arr[arr<2]

array([1])

In [13]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[7,5,9,8,6]

arr=np.array([my_lst1, my_lst2, my_lst3])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [7, 5, 9, 8, 6]])

In [15]:
arr.reshape(15,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [5],
       [9],
       [8],
       [6]])

In [16]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [7, 5, 9, 8, 6]])

In [17]:
arr[1:,3:]

array([[5, 6],
       [8, 6]])

In [18]:
arr[1:,1:3]

array([[3, 4],
       [5, 9]])

In [20]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [24]:
arr=np.arange(3,12,step=3)

In [25]:
arr

array([3, 6, 9])

In [26]:
np.linspace(5,25,10)

array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
       16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ])

In [29]:
lst=[1,2,3,4,5,6,7,8,9]
shri=np.array(lst)

In [30]:
shri

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
shri[2:7]=50

In [32]:
shri

array([ 1,  2, 50, 50, 50, 50, 50,  8,  9])

In [34]:
harsh=shri

In [35]:
harsh[2:7]=50

In [36]:
harsh

array([ 1,  2, 50, 50, 50, 50, 50,  8,  9])

In [38]:
harsh[2:7]=100
harsh

array([  1,   2, 100, 100, 100, 100, 100,   8,   9])

In [39]:
shri

array([  1,   2, 100, 100, 100, 100, 100,   8,   9])