In [1]:
import pickle 
import numpy as np

In [2]:
ohe = pickle.load(open('ohe.pkl', 'rb'))
oe = pickle.load(open('oe.pkl', 'rb'))
clf = pickle.load(open('clf.pkl', 'rb'))

In [9]:
# Assume user input 
test_in = np.array([10, 'Female', 30.0, 'High'], dtype= object).reshape(1,4)

In [10]:
test_in

array([[10, 'Female', 30.0, 'High']], dtype=object)

In [11]:
test_in_gender = ohe.transform(test_in[:,1].reshape(1,1))

C:\Users\dell\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [12]:
test_in_gender

array([[1., 0.]])

In [14]:
test_in_parentSupport = oe.transform(test_in[:,-1].reshape(1,1))

C:\Users\dell\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


In [15]:
test_in_parentSupport

array([[2.]])

In [17]:
test_in_studyhrs = test_in[:, 2].reshape(1,1)

In [26]:
test_in_transformed = np.concatenate((test_in[:,[0]],  test_in_gender, test_in_studyhrs, test_in_parentSupport), axis=1)

In [28]:
test_in_transformed.shape

(1, 5)

In [29]:
clf.predict(test_in_transformed)

array([88], dtype=int64)